const LOCAL_RUNTIME=['127.0.0.1','localhost'].includes(location.hostname)&&location.port==='8765';
const $=id=>document.getElementById(id);let token,report,firmware,plan,busy=false,lastOperation='';const logs=[];
function log(message){logs.push(`[${new Date().toLocaleTimeString()}] ${message}`);$('log').textContent=logs.join('\n');$('log').scrollTop=$('log').scrollHeight}
async function api(path,body,headers={}){if(!LOCAL_RUNTIME)throw Error('This hosted interface cannot access USB devices. Launch the local application at http://127.0.0.1:8765.');const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:{'X-DH-Token':token,...(body instanceof File?{}:{'Content-Type':'application/json'}),...headers},body:body===undefined?undefined:body instanceof File?body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error);return j}
function download(name,data){const url=URL.createObjectURL(new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function invalidate(){plan=null;$('start').disabled=true;$('blocked').textContent='Validate the selected device and package to build a fresh plan.'}
function selected(){return report?.devices.find(d=>d.serial===$('device-select').value)}
function renderDevice(){const d=selected();$('device-name').textContent=d?.model||d?.codename||'No device detected';$('bootloader').textContent=d?.unlocked===true?'Unlocked':d?.unlocked===false?'Locked':'Unknown';$('device-mode').textContent=d?`${d.mode.toUpperCase()} · ${d.state}`:'Waiting for device probe';$('battery').replaceChildren(document.createTextNode(d?.battery??'—'));$('battery-bar').style.width=(d?.battery??0)+'%'}
async function scan(){report=await api('devices');const prev=$('device-select').value;$('device-select').replaceChildren();for(const d of report.devices){const o=document.createElement('option');o.value=d.serial;o.textContent=`${d.serial} · ${d.mode} · ${d.state}`;$('device-select').append(o)}if(!report.devices.length){const o=document.createElement('option');o.textContent='Connect an Android device';o.value='';$('device-select').append(o)}else if(report.devices.some(d=>d.serial===prev))$('device-select').value=prev;renderDevice();$('runtime').textContent=report.execution_enabled?'LOCAL · WRITES ENABLED':'LOCAL · INSPECTION MODE';$('devices-detail').replaceChildren();for(const d of report.devices){const a=document.createElement('article');const h=document.createElement('h2');h.textContent=d.model||d.codename||d.serial;const pre=document.createElement('pre');pre.textContent=JSON.stringify(d,null,2);a.append(h,pre);$('devices-detail').append(a)}log(`Probe: ${report.devices.length} device(s). ADB ${report.tools.adb?'available':'missing'}; Fastboot ${report.tools.fastboot?'available':'missing'}.`)}
async function action(fn){if(busy)return;busy=true;try{await fn()}catch(e){log('ERROR · '+e.message);$('blocked').textContent=e.message}finally{busy=false}}
for(const b of document.querySelectorAll('[data-page]'))b.onclick=()=>{for(const s of ['flash','devices','evidence','guide','settings'])$(s+'-page').hidden=s!==(b.dataset.page==='Inspector'?'flash':b.dataset.page.toLowerCase());document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('selected',x===b));$('page-label').textContent=b.dataset.page;if(b.dataset.page==='Evidence')action(refreshOperations);if(b.dataset.page==='Settings')action(settings);if(b.dataset.page==='Inspector'){$('hash').focus();$('inspect').scrollIntoView({block:'center'})}};
$('device-select').onchange=()=>{invalidate();renderDevice()};$('rescan').onclick=()=>action(async()=>{invalidate();await scan()});
function pick(file){if(!file)return;$('file-name').textContent=file.name;window.packageFile=file;firmware=null;invalidate()}
$('file').onchange=()=>pick($('file').files[0]);$('drop').ondragover=e=>e.preventDefault();$('drop').ondrop=e=>{e.preventDefault();pick(e.dataTransfer.files[0])};$('hash').oninput=()=>{firmware=null;invalidate()};
$('inspect').onclick=()=>action(async()=>{if(!window.packageFile)throw Error('Choose a package first');log('Inspecting archive and publisher signature…');firmware=await api('firmware',window.packageFile,{'X-Firmware-SHA256':$('hash').value.trim().toLowerCase()});$('metadata').replaceChildren();for(const [k,v] of [['Target',firmware.manifest.target],['Signature',firmware.signature],['Partitions',firmware.manifest.partitions.map(p=>p.partition).join(', ')],['SHA-256',firmware.sha256]]){let dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;$('metadata').append(dt,dd)}log('Package hashes and trusted manifest signature verified.');$('progress').value=20;invalidate()});
$('plan').onclick=()=>action(async()=>{if(!firmware)throw Error('Inspect a signed package first');plan=await api('plans',{serial:$('device-select').value,firmware_id:firmware.id});$('gates').replaceChildren();for(const reason of plan.reasons.length?plan.reasons:['All required device and partition gates passed']){const li=document.createElement('li');li.textContent=(plan.allowed?'✓ ':'○ ')+reason;$('gates').append(li)}$('start').disabled=!plan.allowed;$('blocked').textContent=plan.allowed?'Plan valid for five minutes. Review partitions before approving.':plan.reasons.join(' · ');log(plan.allowed?'Plan validated. No writes executed.':'Plan blocked: '+plan.reasons.join('; '));$('progress').value=plan.allowed?40:20});
$('start').onclick=()=>{if(!$('backup').checked||!$('risk').checked){$('blocked').textContent='Both human acknowledgements are required.';return}if(!plan?.allowed)return;$('plan-detail').textContent=JSON.stringify({device:plan.serial,sha256:firmware.sha256,partitions:plan.partitions,automatic_wipe:false,automatic_reboot:false},null,2);$('confirmation').value='';$('confirm').showModal()};
$('confirm-flash').onclick=()=>action(async()=>{if($('confirmation').value!=='FLASH')throw Error('Type FLASH exactly');const a=await api('approvals',{plan_id:plan.id,acknowledgements:{backup:true,risk:true,confirmation:'FLASH'}});const op=await api('execute',{plan_id:plan.id,approval_id:a.approval_id});lastOperation=op.id;$('confirm').close();invalidate();log('Execution started: '+op.id);await refreshOperations()});
async function refreshOperations(){const ops=await api('operations');$('operations').replaceChildren();for(const op of ops){const a=document.createElement('article');const h=document.createElement('h2');h.textContent=op.id;const p=document.createElement('p');p.textContent=op.status+' · '+op.serial;a.append(h,p);if(op.status==='interrupted_unknown'){const warning=document.createElement('p');warning.textContent=op.verification;a.append(warning)}if(op.completed && op.evidence_available!==false && op.status!=='interrupted_unknown'){const b=document.createElement('button');b.textContent='Export signed evidence';b.onclick=()=>action(async()=>download(op.id+'.json',await api('evidence/'+op.id)));a.append(b)}$('operations').append(a);if(op.id===lastOperation){$('operation-status').textContent=op.status.toUpperCase();$('progress').value=Math.round(op.completed_partitions/op.plan.partitions.length*100);$('progress-note').textContent=op.error||op.verification||'Writing firmware; do not disconnect the device.';for(const r of op.logs){const line=JSON.stringify(r);if(!logs.some(x=>x.includes(line)))log(line)}}}}
for(const b of document.querySelectorAll('[data-reboot]'))b.onclick=()=>action(async()=>{invalidate();const r=await api('reboot',{serial:$('device-select').value,mode:b.dataset.reboot});log(JSON.stringify(r));await scan()});
$('verify-file').onchange=()=>action(async()=>{const e=JSON.parse(await $('verify-file').files[0].text());const result=await api('verify-evidence',e);$('verify-result').textContent=result.trusted_local_signer?'Valid signature from this runtime.':'Valid signature; signer is not this runtime.'});$('save-log').onclick=()=>download('dh-flash-log.txt',logs.join('\n'));
(async()=>{if(!LOCAL_RUNTIME){$('runtime').textContent='HOSTED INTERFACE · LOCAL RUNTIME REQUIRED';$('blocked').textContent='Launch the local application to inspect firmware and access USB devices.';$('log').textContent='Hosted interface loaded. No device telemetry or operations are simulated.';for(const id of ['inspect','plan','start','rescan','file','hash','verify-file'])$(id).disabled=true;for(const b of document.querySelectorAll('[data-reboot]'))b.disabled=true;return}try{token=(await(await fetch('/session')).json()).token;await scan();setInterval(()=>{if(lastOperation&&!busy)action(refreshOperations)},2000)}catch(e){log(e.message);$('runtime').textContent='RUNTIME UNAVAILABLE'}})();

let runtimeDiagnostics;
async function settings(){runtimeDiagnostics=await api('diagnostics');$('diagnostics').replaceChildren();const dl=document.createElement('dl');for(const [k,v] of Object.entries(runtimeDiagnostics)){if(k==='capabilities')continue;const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k.replaceAll('_',' ');dd.textContent=typeof v==='object'?JSON.stringify(v):String(v);dl.append(dt,dd)}$('diagnostics').append(dl);$('capabilities').replaceChildren();for(const [key,enabled] of Object.entries(runtimeDiagnostics.capabilities)){const p=document.createElement('p');p.textContent=(enabled?'Available · ':'Unavailable · ')+key.replaceAll('_',' ');$('capabilities').append(p)}}
$('refresh-settings').onclick=()=>action(settings);$('export-diagnostics').onclick=()=>action(async()=>{await settings();download('dh-flash-diagnostics.json',runtimeDiagnostics)});
$('drop').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('file').click()}};
$('confirm').addEventListener('close',()=>$('start').focus());
setInterval(()=>{if(plan&&plan.expires*1000<Date.now()){invalidate();$('blocked').textContent='Plan expired. Build a fresh plan before approving.'}},1000);

$('hosted-notice').hidden=LOCAL_RUNTIME;
